### PR TITLE
transpose a rotation matrix to get a coordinate transformation matrix

### PR DESCRIPTION
**Pull request by estshorter**
The variable `R` should be a coordinate transform matrix from the world coordinate to the camera coordinate.
But `get_rotation_matrix()` returns a inverse matrix.
This PR fixes the issue by transposing (inversing) the matrix.

Ref: https://www.sciencedirect.com/topics/engineering/euler-angle
(see Eq. 9.117 - 9.120

### CODE REVIEW

**Comment by mnslarcher** [comment]
Hi @estshorter , since if R.T is a rotation matrix then R is also a rotation matrix, by using R.T instead of R you are only changing the relationship between the angles theta_x, theta_y and theta_z and the rotation you get. For example if before you were doing a rotation using `theta_x=np.pi / 2.0`, if you use R.T you get the same rotation with `theta_x=-np.pi / 2.0` and vice versa. With R you rotate counterclockwise while with R.T you rotate clockwise, do you agree?

**Comment by estshorter** [comment]
You'll find that your original code has a bug if you set as follows:
```
THETA_X = -np.pi / 2.0  # roll angle
THETA_Y = 0.0  # pitch angle
THETA_Z = 0  # yaw angle
```
results: the purple rectangle should be placed in the left bottom in the second figure, but not.
image

This PR fixes the issue:
image


This is because in https://github.com/mnslarcher/camera-models/blob/a10b3cd4dbad77fa47cd7ddce012f94626562a18/camera-models.ipynb?short_path=4d4c543#L2288-L2290, you regard R (return value of `get_rotation_matrix()`) as a coordinate transform matrix **from the camera coordinate to the world coordinate**.
However, at the same, in https://github.com/mnslarcher/camera-models/blob/a10b3cd4dbad77fa47cd7ddce012f94626562a18/camera_models/_matrices.py#L82-L84, you regard R as a coordinate transform matrix **from the world coordinate to the camera coordinate**.

This is inconsistent.

**Comment by mnslarcher** [comment]
You're right, that is inconsistent!

If you want to, also update the notebook by re-running it and update some angle to get the same results or, if you prefer, I'll merge your PR and do it myself, thanks for the contribution 🙂!

**Comment by estshorter** [comment]
Thanks!
Could you merge this PR and update the notebook by yourself?

**Comment by mnslarcher** [comment]
Sure!

**Pull request merged**
